package app

import (
	_ "awesomeProject/docs" // docs is generated by Swag CLI, you have to import it.
	"awesomeProject/domain"
	"awesomeProject/logger"
	"awesomeProject/service"
	"fmt"
	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
	"log"
)

func Start() {
	//router := mux.NewRouter()

	gin := gin.Default()

	url := ginSwagger.URL("http://localhost:8080/swagger/doc.json") // The url pointing to API definition

	gin.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler, url))

	//mySqlClient := getMySqlClient("root:root@tcp(localhost:3306)/banking")
	mongoClient := getMongoClient("mongodb://localhost:27017")

	// local db/service repositories
	//customerRepositoryDb := domain.NewCustomerRepositoryDb(mySqlClient)
	//accountRepositoryDb := domain.NewAccountRepositoryDb(mySqlClient)
	issueRepository := domain.NewIssueRepositorySql(mongoClient)
	dbReportRepository := domain.NewDbReportRepository(mongoClient)
	// remote db repositories

	// rest handlers
	//ch := CustomerHandlers{service: service.NewCustomerService(customerRepositoryDb)}
	//ah := AccountHandlers{service: service.NewAccountService(accountRepositoryDb)}
	ih := IssueHandlers{service: service.NewIssueService(issueRepository)}
	dbh := DbReportHandlers{service: service.NewDbReportService(dbReportRepository)}
	dh := DownloadHandler{xlsxService: service.NewDbXlsxService(), fileService: service.NewFileService(mongoClient)}
	//ch := CustomerHandlers{service: service.NewCustomerService(domain.NewCustomerRepositoryStub())}

	//// rest routes
	//router.HandleFunc("/customers", ch.getAllCustomers).Methods(http.MethodGet)
	//router.HandleFunc("/customers/{customer_id:[0-9]+}", ch.getCustomer).Methods(http.MethodGet)
	//router.HandleFunc("/customers/{customer_id:[0-9]+}/account", ah.newAccount).Methods(http.MethodPost)
	//router.
	//	HandleFunc("/customers/{customer_id:[0-9]+}/account/{account_id:[0-9]+}", ah.MakeTransaction).
	//	Methods(http.MethodPost).
	//	Name("NewTransaction")

	gin.GET("/issues", ih.getAllIssues)

	gin.GET("/download", dh.downloadXlsx)
	gin.GET("/downloadById", dh.downloadById)

	gin.POST("/issue", ih.CreateIssue)
	//m
	gin.POST("/issuemongo", ih.CreateIssueMongo)

	gin.POST("/issue/create_many", ih.CreateIssues)

	gin.POST("/dbreport", dbh.CreateDbReport)

	// starting server
	fmt.Print(mongoClient.Database("localhost").Collection("ucty").Name())
	logger.Info("Http server start..")
	//log.Fatal(http.ListenAndServe(fmt.Sprintf("%s:%s", "localhost", "8000"), router))
	log.Fatal(gin.Run())
}
