definitions:
  domain.Issue:
    properties:
      accountId:
        type: string
      createdAt:
        type: string
      description:
        type: string
      id:
        type: string
      name:
        type: string
      status:
        type: number
    type: object
  dto.CreateIssueRequest:
    properties:
      account_id:
        type: string
      description:
        type: string
      name:
        type: string
    type: object
  errs.AppError:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
info:
  contact:
    email: ratpile@gmail.com
    name: API Support
  description: Swagger API for Golang Testigo project
  termsOfService: http://swagger.io/terms/
  title: Testigo Swagger API
  version: "1.0"
paths:
  /issue:
    post:
      consumes:
      - application/json
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.CreateIssueRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Issue'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errs.AppError'
      summary: Create issue
  /issues:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.Issue'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errs.AppError'
      summary: Retrieves list of Issues
swagger: "2.0"
